config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  root 'static_pages#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/home', to: 'static_pages#home'
  get '/alternatives', to: 'static_pages#alternatives'
  get '/issues', to: 'static_pages#issues'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :stocks, only: [:index, :show]
  resources :posts
  resources :users
  resources :relationships, only: [:create, :destroy]
  resources :ledgers, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  attr_accessor :remember_token
  has_secure_password
  has_many :posts

  has_many :ledgers
  has_many :assets, through: :ledgers, source: :stock

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 249}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence: true

  #add ledger item for this user and asset
  def invest(stock)
    assets << stock
  end

  #check if a user is holding an asset
  def holding?(stock)
    assets.include?(stock)
  end

  #delete a ledger item
  def divest(stock)
    ledgers.destroy(Ledger.find_by({stock_id: stock}))
  end

  #check if this user is following the person whose page this is
  def following?(user)
    followers.include?(user)
  end

  #follow another User
  def follow(user)
    followers << user
  end

  #unfollow current User
  def unfollow(user)
    followers.delete(user)
  end

  #return digest of given string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #return random token for cookies
  def User.new_token
    SecureRandom.urlsafe_base64
  end


  def remember
    self.remember_token = User.new_token
    update_attribute(:rem_hash, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if rem_hash.nil?
    BCrypt::Password.new(rem_hash).is_password?(remember_token)
  end

  def forget
    update_attribute(:rem_hash, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :following, :followers]
  before_action :check_login, only: [:edit, :index, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @userposts = @user.posts
    @userstocks = @user.ledgers
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)


    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def following
    @title = "Following"
    @userlist = @user.followers
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @userlist = @user.following
    render 'show_follow'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def check_login
      unless logged_in?
        flash[:danger] = "You have to log in"
        redirect_to login_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "follow-button" %>
<%end%>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password%>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.text_field :password_confirmation, id: :user_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(@user.active_relationships.find_by!(followed_id: current_user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "unfollow-button" %>
<%end%>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Pass hash</th>
      <th>Rem hash</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.rem_hash %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div id="user-show">
  <div id="sidebar" class="col-md-4">
    <div id="bio">
      <h3> Bio </h3>
      <p>
        <strong>Name:</strong>
        <%= @user.name %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @user.email %>
      </p>
      <% unless current_user?(@user) %>
        <div id="follow_button">
        <% if current_user.following?(@user) %>
          <%= render 'unfollow' %>
        <% else %>
          <%= render 'follow' %>
        <% end %>
        </div>
      <% end %>
      <footer id="connections">
        <aside id="following">
          <a href="<%= following_user_path(@user) %>">
            <header>Following</header><footer><%= @user.followers.count %></footer>
          </a>
        </aside>
        <aside id="followers">
          <a href="<%= followers_user_path(@user) %>">
            <header>Followers</header><footer><%= @user.following.count %></footer>
          </a>
        </aside>
      </footer>
    </div>
    <div id="portfolio">
      <h3> Portfolio </h3>
      <ul>
        <% @userstocks.each do |s| %>
        <% stock = Stock.find_by({id: s.stock_id}) %>
          <li><span class="company"><%= link_to(stock.company, stock) %></span></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div id="userposts" class="col-md-8">
    <h3> My Posts </h3>
    <% if @user.id == current_user.id%>
      <%= link_to 'New Post', new_post_path %>
    <% end %>
    <ul>
      <% @userposts.each do |p| %>
        <li>
          <span class="company">
            <%stock = Stock.find(p.stock_id)%>
            <h5><%= link_to(stock.company, stock) %></h5>
          </span>
           <%= p.content %>
         </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title)%>

<h4><%= @title %></h4>

<table id="connections">
  <thead>
    <strong><th> Name </th></strong>
    <strong><th> Email </th></strong>
  </thead>

  <% @userlist.each do |connect| %>
  <tbody>
    <tr class="user-list">
      <td><a href="<%= user_path(connect.id)%>"><%= connect.name %></a></td>
      <td><%= connect.email %></td>
    </tr>
  </tbody>
  <%end%>
</table>