config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  root 'static_pages#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/home', to: 'static_pages#home'
  get '/alternatives', to: 'static_pages#alternatives'
  get '/issues', to: 'static_pages#issues'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :stocks, only: [:index, :show]
  resources :posts
  resources :users
  resources :relationships, only: [:create, :destroy]
  resources :ledgers, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<nav class='navbar navbar-default'>
  <div class='container-fluid'>
    <div class='navbar-links'>
      <ul>
        <% if logged_in? %>
          <li class="left"> Hi, <%= current_user.name %> <li>
          <li class="right"><%= link_to 'Home', posts_path, role: 'button' %></li>
          <li class="right"><%= link_to 'Stocks', stocks_path, role: 'button' %></li>
          <li class="right"><%= link_to 'Profile', current_user, role: 'button' %></li>
          <li class="right" role='presentation'><%= link_to 'Logout', logout_path, method: :delete, role: 'button' %></li>
        <% else %>
          <li class="left"><%= link_to 'Home', root_path, role: 'button' %></li>
          <li class="left"><%= link_to 'Stocks', stocks_path, role: 'button' %></li>
          <li class="right" role='presentation'><%= link_to 'Login', login_path, role: 'button' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stocks</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', 'bootstrap', 'nav', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body class='vsc-initialized'>
    <div id='page' class='wrapper'>
      <div class='main-panel'>
        <%= render 'layouts/nav' %>
        <div class='content'>
          <div class='container-fluid'>
            <div class='card'>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>